import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../../services/supabase';

interface ImportRecord { id:string; meal_date:string; status:string; validation_status:string; validation_report:{errors?:string[];warnings?:string[]}; breakfast_total:number;lunch_total:number;dinner_total:number;storage_path?:string|null;created_at:string;processed_at?:string|null;ocr_import_rows:Array<{id:string;detected_name:string;matched_member_id?:string|null;breakfast:boolean;lunch:boolean;dinner:boolean;confidence?:number|null;needs_review:boolean;notes?:string|null}>; }

function OcrHistory() {
  const [items,setItems]=useState<ImportRecord[]>([]); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(false); const [images,setImages]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{setLoading(true);let query=supabase.from('ocr_imports').select('*,ocr_import_rows(*)').order('created_at',{ascending:false}).limit(50);if(status!=='all')query=query.eq('status',status);const{data,error}=await query;if(error)console.error(error);else setItems((data||[]) as ImportRecord[]);setLoading(false);},[status]);
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('ocr:changed',refresh);return()=>window.removeEventListener('ocr:changed',refresh);},[load]);
  const showImage=async(item:ImportRecord)=>{if(!item.storage_path)return;const{data,error}=await supabase.storage.from('whiteboard-images').createSignedUrl(item.storage_path,300);if(!error)setImages(current=>({...current,[item.id]:data.signedUrl}));};
  return <section className="card"><div className="flex items-center justify-between mb-4"><div><h3 className="text-lg font-semibold text-text-primary">OCR History</h3><p className="text-sm text-text-secondary">Stored whiteboards, extracted rows, and validation results</p></div><select className="input" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All</option><option value="ready">Ready</option><option value="validation_failed">Needs review</option><option value="applied">Applied</option><option value="failed">Failed</option></select></div>
  {loading?<div className="py-6 text-center text-text-secondary">Loading...</div>:<div className="space-y-3">{items.map(item=><details key={item.id} className="border border-border rounded-lg"><summary className="p-3 cursor-pointer flex flex-wrap justify-between gap-2"><span className="font-medium text-text-primary">{item.meal_date}</span><span className="text-sm text-text-secondary">B {item.breakfast_total} · L {item.lunch_total} · D {item.dinner_total} · {item.status} · {new Date(item.processed_at||item.created_at).toLocaleString()}</span></summary><div className="p-3 border-t border-border space-y-3">
    {item.storage_path&&<div><button className="btn-secondary px-3 py-2 text-sm" onClick={()=>void showImage(item)}>View original</button>{images[item.id]&&<img src={images[item.id]} alt={`Whiteboard ${item.meal_date}`} className="mt-3 max-h-96 w-auto border border-border rounded" />}</div>}
    {(item.validation_report?.errors||[]).map(value=><div key={value} className="text-sm text-error">{value}</div>)}{(item.validation_report?.warnings||[]).map(value=><div key={value} className="text-sm text-warning">{value}</div>)}
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-bg-tertiary"><th className="p-2 text-left">Detected</th><th>B</th><th>L</th><th>D</th><th>Confidence</th></tr></thead><tbody>{item.ocr_import_rows.map(row=><tr key={row.id} className="border-t border-border"><td className="p-2">{row.detected_name}</td><td className="text-center">{row.breakfast?'Y':'-'}</td><td className="text-center">{row.lunch?'Y':'-'}</td><td className="text-center">{row.dinner?'Y':'-'}</td><td className="text-center">{row.confidence==null?'-':`${Math.round(row.confidence*100)}%`}</td></tr>)}</tbody></table></div>
  </div></details>)}</div>}</section>;
}
export default OcrHistory;
